config/routes.rb
Rails.application.routes.draw do
  resources :products, :comments
  root :to => 'products#index'
  get 'products/index'
  
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, :image_url, :presence => true# khong duoc bo trong
    validates :price, :numericality => {:greater_than_or_equal_to => 1000}#gia tri nhap vao lon hon 1000
    validates :title, :uniqueness => true #duy nhat, khong the giong nhau
    validates :image_url, :format => {
        :with => %r{\.(gif|jpg|png)\Z}i,
        :message => 'Chi nhan file GIF, JPG, PNG'}


    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index 
    @q = Product.ransack(params[:q])
    @products = @q.result
  end


  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :sku, :price, :quantity, :image_url, :term)
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div id=banner>
          <h1> BOOK STORE </h1>
    </div>
    <div id="columns">
        <div id="side">
            <strong> 
              <a href="#">Home</a><br />
              <%= link_to 'Products', root_path %><br />
              <a href="#">News</a><br />
              <a href="#">Contact</a><br /> </strong>
        </div>
        <div id="main">
            <%= yield %>
        </div>
    </div> 
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
    <h1>All Products</h1>
    <%= search_form_for @q do |f| %>
       <b> <%= f.label 'SEARCH FOR' %> </b>
        <%= f.search_field :title_cont %>
        <%= f.submit %>
    <% end %>

    <table>
    <% @products.each do |product| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  
            <td>
                <%= image_tag(product.image_url, :class => 'list_image') %>
            </td> 
  
            <td class="list_title">
                <dl>
                    <dt><%= product.title %></dt>
                    <dt>
                        <p>
                        Price: 
                        <%= product.price %>
                        </p>
                    </dt>
                </dl>
            </td>
           
            <td class="list_actions">
                <%= link_to 'Show', product %><br/>
                <%= link_to 'Edit', edit_product_path(product) %><br/>
                <%= link_to 'Destroy', product,data: { confirm: 'Are you sure?' },:method => :delete %>
            </td>
        </tr>
    <% end %>
    </table>
</div>
 
<br />
 
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<big> 
<b>
  <%= @product.title%>
</b>
</big>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
      <div class='field'>
        <%= image_tag(@product.image_url, style: 'width: 900px;
    height: 500px')%>
      </div>
  </p> 
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>